// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9SgRGV60UM9-_lp11dlIRfZkiqtO4nuM',
    appId: '1:707489891015:web:771b571928c77a19ec74e2',
    messagingSenderId: '707489891015',
    projectId: 'apnamart-9bc50',
    authDomain: 'apnamart-9bc50.firebaseapp.com',
    storageBucket: 'apnamart-9bc50.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTq-8L6THh24IXjMjCr8THKnhcL4lYvLM',
    appId: '1:707489891015:android:a1bc6142e8b2a977ec74e2',
    messagingSenderId: '707489891015',
    projectId: 'apnamart-9bc50',
    storageBucket: 'apnamart-9bc50.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBshJfP1Zs-AZKHbEGfmuzpVpJukRQtvEE',
    appId: '1:707489891015:ios:017955bf4a8ce8baec74e2',
    messagingSenderId: '707489891015',
    projectId: 'apnamart-9bc50',
    storageBucket: 'apnamart-9bc50.appspot.com',
    iosBundleId: 'com.example.apnaMart',
  );
}
